### ISSUE TITLE
[Beta React Docs] New Albanian Translation Progress

### ISSUE THREAD

**Issue by theringsofsaturn** [reactjs/sq.reactjs.org#48]
# ⚠ [Beta Website](https://beta.reactjs.org/)⚠ 

All the ongoing translations for the current docs will be suspended, as it only makes sense to focus on the new website content now. Dan Abramov suggested not to put extra energy into translating the current content.

## Maintainer List

* [theringsofsaturn](https://github.com/theringsofsaturn)

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know, so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@theringsofsaturn) #48

When PRs are merged, make sure to mark that page as completed!

## What is ok to translate now?

The new docs aren't fully written yet, and some parts will definitely change. However, a lot of the pages are already "stable". It is suggested to use this checklist for the beginning. ✅ means "ok to translate", 🔴 means "don't translate yet".

(Updated on Feb 12: more pages ok to translate.) Ref: (https://github.com/reactjs/reactjs.org/issues/4135)

- [ ] ✅ Installation (note: a lot of content here is similar to old website) ✅ FINISHED [theringsofsaturn](https://github.com/theringsofsaturn)
  - [ ] ✅ Start a New React Project ✅ FINISHED by [theringsofsaturn](https://github.com/theringsofsaturn)
  - [ ] ✅ Add React to a Website ✅ FINISHED by [theringsofsaturn](https://github.com/theringsofsaturn)
  - [ ] ✅ Editor Setup ✅ FINISHED by [theringsofsaturn](https://github.com/theringsofsaturn)
  - [ ] ✅ React Developer Tools ✅ FINISHED by [theringsofsaturn](https://github.com/theringsofsaturn)
- [ ] ✅ Quick Start ✅ FINISHED by [theringsofsaturn](https://github.com/theringsofsaturn) 
  - [ ] ✅ Thinking in React ⚠ Work in progress by [theringsofsaturn](https://github.com/theringsofsaturn)
- [ ] ✅ Describing the UI
  - [ ] ✅ Your First Component
  - [ ] ✅ Importing and Exporting Components
  - [ ] ✅ Writing Markup with JSX
  - [ ] ✅ JavaScript in JSX with Curly Braces
  - [ ] ✅ Passing Props to a Component
  - [ ] ✅ Conditional Rendering
  - [ ] ✅ Rendering Lists
  - [ ] ✅ Keeping Components Pure
- [ ] ✅ Adding Interactivity
  - [ ] ✅ Responding to Events
  - [ ] ✅ State: A Component's Memory
  - [ ] ✅ Render and Commit
  - [ ] ✅ State as a Snapshot
  - [ ] ✅ Queueing a Series of State Updates
  - [ ] ✅ Updating Objects in State
  - [ ] ✅ Updating Arrays in State
- [ ] ✅ Managing State
  - [ ] ✅ Reacting to Input with State
  - [ ] ✅ Choosing the State Structure
  - [ ] ✅ Sharing State Between Components
  - [ ] ✅ Preserving and Resetting State
  - [ ] ✅ Extracting State Logic into a Reducer
  - [ ] ✅ Passing Data Deeply with Context
  - [ ] ✅ Scaling Up with Reducer and Context
- [ ] 🔴 Escape Hatches (not written yet)
  - [ ] ✅ Referencing Values with Refs
  - [ ] ✅ Manipulating the DOM with Refs
- API
  - [ ] ✅ React APIs (ok to translate, but incomplete)
    - [ ] ✅ useState
  - [ ] ✅ React DOM APIs (ok to translate, but incomplete)
    - [ ] ✅ render
    
## How to translate?
    
Currently, the beta website is in the beta folder. So all existing translation repos should have it synced (if the sync script is working). So you can follow the existing process. If something doesn't work, please comment here, so we can ask then to [Beta translation upstream (#4135)](https://github.com/reactjs/reactjs.org/issues/4135)

If we are able to translate at least three pages, we can ask the team to setup a deployment for us.

## Something unclear?

Please comment here with concerns or suggestions.

**Comment by theringsofsaturn** [comment]
I'm currently translating "Start a New React Project" and "Add React to a Website".

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
